var annotated =
[
    [ "nrg", null, [
      [ "BitWriter", "classnrg_1_1BitWriter.html", "classnrg_1_1BitWriter" ],
      [ "BitReader", "classnrg_1_1BitReader.html", "classnrg_1_1BitReader" ],
      [ "Client", "classnrg_1_1Client.html", "classnrg_1_1Client" ],
      [ "ClientHandshakeState", "classnrg_1_1ClientHandshakeState.html", "classnrg_1_1ClientHandshakeState" ],
      [ "ClientGameState", "classnrg_1_1ClientGameState.html", "classnrg_1_1ClientGameState" ],
      [ "Codec", "structnrg_1_1Codec.html", "structnrg_1_1Codec" ],
      [ "Codec< T, typename enable_if< has_encode_decode< T >::value >::type >", "structnrg_1_1Codec_3_01T_00_01typename_01enable__if_3_01has__encode__decode_3_01T_01_4_1_1value_01_4_1_1type_01_4.html", "structnrg_1_1Codec_3_01T_00_01typename_01enable__if_3_01has__encode__decode_3_01T_01_4_1_1value_01_4_1_1type_01_4" ],
      [ "Codec< char[len]>", "structnrg_1_1Codec_3_01char[len]_4.html", "structnrg_1_1Codec_3_01char[len]_4" ],
      [ "Codec< std::string >", "structnrg_1_1Codec_3_01std_1_1string_01_4.html", "structnrg_1_1Codec_3_01std_1_1string_01_4" ],
      [ "ConnectionCommon", "structnrg_1_1ConnectionCommon.html", "structnrg_1_1ConnectionCommon" ],
      [ "ConnectionIn", "classnrg_1_1ConnectionIn.html", "classnrg_1_1ConnectionIn" ],
      [ "ConnectionOut", "classnrg_1_1ConnectionOut.html", "classnrg_1_1ConnectionOut" ],
      [ "Connection", "structnrg_1_1Connection.html", "structnrg_1_1Connection" ],
      [ "Entity", "classnrg_1_1Entity.html", "classnrg_1_1Entity" ],
      [ "EntityManager", "structnrg_1_1EntityManager.html", "structnrg_1_1EntityManager" ],
      [ "EntityHelper", "structnrg_1_1EntityHelper.html", "structnrg_1_1EntityHelper" ],
      [ "DisconnectEvent", "structnrg_1_1DisconnectEvent.html", "structnrg_1_1DisconnectEvent" ],
      [ "EntityEvent", "structnrg_1_1EntityEvent.html", "structnrg_1_1EntityEvent" ],
      [ "PlayerEvent", "structnrg_1_1PlayerEvent.html", "structnrg_1_1PlayerEvent" ],
      [ "Event", "unionnrg_1_1Event.html", "unionnrg_1_1Event" ],
      [ "EventQueue", "classnrg_1_1EventQueue.html", "classnrg_1_1EventQueue" ],
      [ "FieldBase", "classnrg_1_1FieldBase.html", "classnrg_1_1FieldBase" ],
      [ "FieldContainer", "structnrg_1_1FieldContainer.html", "structnrg_1_1FieldContainer" ],
      [ "Field", "classnrg_1_1Field.html", "classnrg_1_1Field" ],
      [ "Field< T[N]>", "classnrg_1_1Field_3_01T[N]_4.html", "classnrg_1_1Field_3_01T[N]_4" ],
      [ "InputBase", "structnrg_1_1InputBase.html", "structnrg_1_1InputBase" ],
      [ "Input", "structnrg_1_1Input.html", "structnrg_1_1Input" ],
      [ "lerp", "structnrg_1_1lerp.html", "structnrg_1_1lerp" ],
      [ "MessageBase", "structnrg_1_1MessageBase.html", "structnrg_1_1MessageBase" ],
      [ "Message", "classnrg_1_1Message.html", "classnrg_1_1Message" ],
      [ "MessageManager", "classnrg_1_1MessageManager.html", "classnrg_1_1MessageManager" ],
      [ "NetAddress", "classnrg_1_1NetAddress.html", "classnrg_1_1NetAddress" ],
      [ "PacketReadable", "structnrg_1_1PacketReadable.html", "structnrg_1_1PacketReadable" ],
      [ "PacketWritable", "structnrg_1_1PacketWritable.html", "structnrg_1_1PacketWritable" ],
      [ "Packet", "classnrg_1_1Packet.html", "classnrg_1_1Packet" ],
      [ "PacketTransformation", "structnrg_1_1PacketTransformation.html", "structnrg_1_1PacketTransformation" ],
      [ "PacketHeader", "structnrg_1_1PacketHeader.html", "structnrg_1_1PacketHeader" ],
      [ "Player", "structnrg_1_1Player.html", "structnrg_1_1Player" ],
      [ "Queue", "classnrg_1_1Queue.html", "classnrg_1_1Queue" ],
      [ "ReplayRecorder", "classnrg_1_1ReplayRecorder.html", "classnrg_1_1ReplayRecorder" ],
      [ "ReplayServer", "classnrg_1_1ReplayServer.html", "classnrg_1_1ReplayServer" ],
      [ "RingBuffer", "classnrg_1_1RingBuffer.html", "classnrg_1_1RingBuffer" ],
      [ "Server", "classnrg_1_1Server.html", "classnrg_1_1Server" ],
      [ "ServerHandshakeState", "structnrg_1_1ServerHandshakeState.html", "structnrg_1_1ServerHandshakeState" ],
      [ "ServerPlayerGameState", "classnrg_1_1ServerPlayerGameState.html", "classnrg_1_1ServerPlayerGameState" ],
      [ "Snapshot", "classnrg_1_1Snapshot.html", "classnrg_1_1Snapshot" ],
      [ "DeltaSnapshot", "structnrg_1_1DeltaSnapshot.html", "structnrg_1_1DeltaSnapshot" ],
      [ "ClientSnapshot", "structnrg_1_1ClientSnapshot.html", "structnrg_1_1ClientSnapshot" ],
      [ "Socket", "classnrg_1_1Socket.html", "classnrg_1_1Socket" ],
      [ "UDPSocket", "structnrg_1_1UDPSocket.html", "structnrg_1_1UDPSocket" ],
      [ "StateConnectionOut", "structnrg_1_1StateConnectionOut.html", "structnrg_1_1StateConnectionOut" ],
      [ "State", "structnrg_1_1State.html", "structnrg_1_1State" ],
      [ "StateConnectionOutImpl", "structnrg_1_1StateConnectionOutImpl.html", "structnrg_1_1StateConnectionOutImpl" ],
      [ "TransitionState", "structnrg_1_1TransitionState.html", "structnrg_1_1TransitionState" ],
      [ "StateManager", "classnrg_1_1StateManager.html", "classnrg_1_1StateManager" ],
      [ "Status", "structnrg_1_1Status.html", "structnrg_1_1Status" ],
      [ "StatusOK", "structnrg_1_1StatusOK.html", "structnrg_1_1StatusOK" ],
      [ "StatusErr", "structnrg_1_1StatusErr.html", "structnrg_1_1StatusErr" ],
      [ "IDAssigner", "classnrg_1_1IDAssigner.html", "classnrg_1_1IDAssigner" ],
      [ "ClientStats", "structnrg_1_1ClientStats.html", "structnrg_1_1ClientStats" ],
      [ "min_sizeof", "structnrg_1_1min__sizeof.html", null ],
      [ "size2type", "structnrg_1_1size2type.html", null ],
      [ "size2type< 1 >", "structnrg_1_1size2type_3_011_01_4.html", "structnrg_1_1size2type_3_011_01_4" ],
      [ "size2type< 2 >", "structnrg_1_1size2type_3_012_01_4.html", "structnrg_1_1size2type_3_012_01_4" ],
      [ "size2type< 4 >", "structnrg_1_1size2type_3_014_01_4.html", "structnrg_1_1size2type_3_014_01_4" ],
      [ "size2type< 8 >", "structnrg_1_1size2type_3_018_01_4.html", "structnrg_1_1size2type_3_018_01_4" ],
      [ "TVarint", "structnrg_1_1TVarint.html", null ],
      [ "TVarint< T, typename std::enable_if< std::is_unsigned< T >::value >::type >", "structnrg_1_1TVarint_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__unsigned_3_01T_01_4_1_1value_01_4_1_1type_01_4.html", "structnrg_1_1TVarint_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__unsigned_3_01T_01_4_1_1value_01_4_1_1type_01_4" ],
      [ "TVarint< T, typename std::enable_if< std::is_signed< T >::value >::type >", "structnrg_1_1TVarint_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__signed_3_01T_01_4_1_1value_01_4_1_1type_01_4.html", "structnrg_1_1TVarint_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__signed_3_01T_01_4_1_1value_01_4_1_1type_01_4" ],
      [ "Version", "structnrg_1_1Version.html", "structnrg_1_1Version" ]
    ] ]
];